package neverless.domain.event;

public enum EventType {

    EVENT_NEW_GAME,
    EVENT_DIALOG_START,
    EVENT_DIALOG_PHRASE_SELECTED,
    EVENT_MAP_GO_DOWN,
    EVENT_MAP_GO_UP,
    EVENT_MAP_GO_LEFT,
    EVENT_MAP_GO_RIGHT,
    EVENT_MAP_IMPASSABLE
}
