package neverless.dto.screendata.event;

public enum EventType {

    MAP_GO_EVENT,
    MAP_GO_IMPOSSIBLE_EVENT,
    DIALOG_START_EVENT,
    DIALOG_SELECT_PHRASE_EVENT,
    RIGHT_HAND_EQUIP_EVENT,
    LEFT_HAND_EQUIP_EVENT,
    JOURNAL_UPDATED_EVENT,
    PORTAL_ENTER_EVENT,
}
